apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kyosm-storage
provisioner: rancher.io/local-path
parameters:
  nodePath: /data/kyosm
  pathPattern: "{{ .PVC.Name }}"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer