apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magento-pvc
  namespace: customer-service
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kyosm-storage
  resources:
    requests:
      storage: 20Gi